### ISSUE TITLE
Decoding not work with real data

### ISSUE THREAD

**Issue by LeeroyDing** [AntonFagerberg/elixir_bencode#1]
Trying to decode messages replied by bootstrapping nodes and it shows invalid format. Looks like the length of encoded string differs from its binary size (unicode string?).

Will issue a PR soon.

**Comment by LeeroyDing** [comment]
PR isssued #2

**Comment by AntonFagerberg** [comment]
I've looked at your PR now (thank you!) and I'm afraid that it won't work.
When I first created this library, I used the String module like you do but I ran into problems when working with torrent files (I have added a test for this: d2994e8304deef59cfe3b70cf9c2b6d318de6e1b).

As an example, you can try downloading the file http://cdimage.debian.org/debian-cd/8.0.0/amd64/bt-cd/debian-8.0.0-amd64-CD-1.iso.torrent and then do a `File.read!("debian-8.0.0-amd64-CD-1.iso.torrent") |> Bencode.decode!`. This will work when dealing with raw bytes (I guess since the "pieces" are raw bytes) but not with the String module.

If we look at Wikipedia regarding Bencode:
"A byte string (a sequence of bytes, **not necessarily characters**)"
and
"The specification does not deal with encoding of characters outside the ASCII set; to mitigate this, some BitTorrent applications explicitly communicate the encoding (most commonly UTF-8) in various non-standard ways. This is identical to how netstrings work, except that netstrings additionally append a comma suffix after the byte sequence."

I'm curious what kind of messages that you run into problems with and whether the problem is in this library or in the sender of messages. I would be happy to work with you to figure this out but I need more details about the problem you have.

If you can show the message which is causing the problem and perhaps some documentation, I can take closer look at it!

**Comment by LeeroyDing** [comment]
This is strange. I was trying to parse response from `route.bittorrent.com:6881` but it won't work. I'll look at it later today.

**Comment by AntonFagerberg** [comment]
@LeeroyDing Have you been able to replicate the problem you had? Otherwise I would like to close this issue. :)

**Comment by LeeroyDing** [comment]
sorry, haven't got time to figure it out, will come back if there's any problem :)
